# This is a workflow to build and deploy the rust project to Github Pages 
# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  check:
    name: rust project
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Checkout rustviz_tut repo on current branch 
          uses: actions/checkout@v2
          with:
            repository: rustviz/rustviz-tutorial
            path: rustviz_tut
        - name: Checkout rustviz  repo on current branch
          uses: actions/checkout@v2
          with:
            repository: rustviz/rustviz
            path: rustviz
        - run: cd rustviz_tut
        - run: sh copy_assets.sh
        - run: mv githubLogging.js logging.js
        - run: cargo install mdbook
        - run: mdbook build
        - name: rust project
          if: success()
          uses: crazy-max/ghaction-github-pages@v2
          with:
            target_branch: gh-pages
            build_dir: book
            keep_history: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}